# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: 3

tasks:
  dev:
    desc: Run the program directly
    cmd: "go run . -d example"
  lint:
    desc: Lint all files
    cmd: "golangci-lint run"
